const AUDIT_ACTIONS = {
  MERCHANT_LOGIN: "MERCHANT_LOGIN",
  AGENT_LOGIN: "AGENT_LOGIN",
  TICKET_CREATED: "TICKET_CREATED",
  TICKET_ASSIGNED: "TICKET_ASSIGNED",
  TICKET_TRANSFERRED: "TICKET_TRANSFERRED",
  STATUS_CHANGED: "STATUS_CHANGED",
  REPLY_ADDED: "REPLY_ADDED",
  INTERNAL_NOTE_ADDED: "INTERNAL_NOTE_ADDED",
  ATTACHMENT_UPLOADED: "ATTACHMENT_UPLOADED"
};

const ACTOR_TYPES = {
  AGENT: "AGENT",
  MERCHANT: "MERCHANT",
  SYSTEM: "SYSTEM"
};

const ENTITY_TYPES = {
  TICKET: "TICKET",
  USER: "USER",
  MERCHANT: "MERCHANT"
};

module.exports = { AUDIT_ACTIONS, ACTOR_TYPES, ENTITY_TYPES };
