const AUDIT_ACTIONS = {
  MERCHANT_LOGIN: "MERCHANT_LOGIN",
  AGENT_LOGIN: "AGENT_LOGIN",
  TICKET_CREATED: "TICKET_CREATED",
  TICKET_ASSIGNED: "TICKET_ASSIGNED",
  TICKET_TRANSFERRED: "TICKET_TRANSFERRED",
  STATUS_CHANGED: "STATUS_CHANGED",
  REPLY_ADDED: "REPLY_ADDED",
  INTERNAL_NOTE_ADDED: "INTERNAL_NOTE_ADDED",
  ATTACHMENT_UPLOADED: "ATTACHMENT_UPLOADED",
  TICKET_CLASSIFIED: "TICKET_CLASSIFIED",
  // Phase 11 — workspace / staff / configuration
  USER_INVITED: "USER_INVITED",
  USER_INVITATION_RESENT: "USER_INVITATION_RESENT",
  USER_INVITATION_REVOKED: "USER_INVITATION_REVOKED",
  USER_SUSPENDED: "USER_SUSPENDED",
  USER_REACTIVATED: "USER_REACTIVATED",
  USER_DEACTIVATED: "USER_DEACTIVATED",
  WORKSPACE_ORGANIZATION_UPDATED: "WORKSPACE_ORGANIZATION_UPDATED",
  WORKSPACE_BRANDING_UPDATED: "WORKSPACE_BRANDING_UPDATED",
  WORKSPACE_LOGO_UPLOADED: "WORKSPACE_LOGO_UPLOADED",
  WORKSPACE_LOGO_DELETED: "WORKSPACE_LOGO_DELETED",
  WORKSPACE_SETUP_COMPLETED: "WORKSPACE_SETUP_COMPLETED",
  WORKSPACE_SETUP_SKIPPED: "WORKSPACE_SETUP_SKIPPED",
  APPLICATION_CREATED: "APPLICATION_CREATED",
  APPLICATION_UPDATED: "APPLICATION_UPDATED",
  APPLICATION_DELETED: "APPLICATION_DELETED",
  TEAM_CREATED: "TEAM_CREATED",
  TEAM_UPDATED: "TEAM_UPDATED",
  TEAM_DELETED: "TEAM_DELETED",
  MODULE_CREATED: "MODULE_CREATED",
  MODULE_UPDATED: "MODULE_UPDATED",
  MODULE_DELETED: "MODULE_DELETED",
  CLIENT_CREATED: "CLIENT_CREATED",
  CLIENT_UPDATED: "CLIENT_UPDATED",
  CLIENT_DELETED: "CLIENT_DELETED"
};

const ACTOR_TYPES = {
  AGENT: "AGENT",
  MERCHANT: "MERCHANT",
  SYSTEM: "SYSTEM"
};

const ENTITY_TYPES = {
  TICKET: "TICKET",
  USER: "USER",
  MERCHANT: "MERCHANT",
  APPLICATION: "APPLICATION",
  TEAM: "TEAM",
  MODULE: "MODULE",
  WORKSPACE: "WORKSPACE"
};

module.exports = { AUDIT_ACTIONS, ACTOR_TYPES, ENTITY_TYPES };
