/**
 * ELVA Central Support operational identity (support.elvasupport.in).
 * Completely separate from Platform Admin (admin.elvasupport.in) and tenant staff.
 */

const CENTRAL_SUPPORT_IDENTITY_TYPE = "CENTRAL_SUPPORT";

const CENTRAL_SUPPORT_ROLES = Object.freeze({
  CENTRAL_SUPPORT_ADMIN: "CENTRAL_SUPPORT_ADMIN",
  CENTRAL_SUPPORT_TEAM_LEAD: "CENTRAL_SUPPORT_TEAM_LEAD",
  CENTRAL_SUPPORT_AGENT: "CENTRAL_SUPPORT_AGENT"
});

const ALL_CENTRAL_SUPPORT_ROLES = Object.values(CENTRAL_SUPPORT_ROLES);

/** Roles that may be assigned tickets (all operational roles). */
const CENTRAL_SUPPORT_ASSIGNABLE_ROLES = Object.freeze([
  CENTRAL_SUPPORT_ROLES.CENTRAL_SUPPORT_ADMIN,
  CENTRAL_SUPPORT_ROLES.CENTRAL_SUPPORT_TEAM_LEAD,
  CENTRAL_SUPPORT_ROLES.CENTRAL_SUPPORT_AGENT
]);

const CENTRAL_SUPPORT_USER_STATUSES = Object.freeze({
  ACTIVE: "ACTIVE",
  INVITED: "INVITED",
  SUSPENDED: "SUSPENDED",
  DISABLED: "DISABLED"
});

const ALL_CENTRAL_SUPPORT_USER_STATUSES = Object.values(CENTRAL_SUPPORT_USER_STATUSES);

const CENTRAL_SUPPORT_ERROR_CODES = Object.freeze({
  CENTRAL_SUPPORT_ACCESS_DENIED: "CENTRAL_SUPPORT_ACCESS_DENIED",
  CENTRAL_SUPPORT_USER_INACTIVE: "CENTRAL_SUPPORT_USER_INACTIVE",
  CENTRAL_SUPPORT_USER_NOT_FOUND: "CENTRAL_SUPPORT_USER_NOT_FOUND",
  CENTRAL_SUPPORT_EMAIL_EXISTS: "CENTRAL_SUPPORT_EMAIL_EXISTS",
  INVALID_CENTRAL_SUPPORT_ROLE: "INVALID_CENTRAL_SUPPORT_ROLE",
  INVALID_CENTRAL_SUPPORT_CREDENTIALS: "INVALID_CENTRAL_SUPPORT_CREDENTIALS",
  CENTRAL_SUPPORT_TEAM_NOT_FOUND: "CENTRAL_SUPPORT_TEAM_NOT_FOUND",
  INVALID_ASSIGNEE: "INVALID_CENTRAL_SUPPORT_ASSIGNEE"
});

module.exports = {
  CENTRAL_SUPPORT_IDENTITY_TYPE,
  CENTRAL_SUPPORT_ROLES,
  ALL_CENTRAL_SUPPORT_ROLES,
  CENTRAL_SUPPORT_ASSIGNABLE_ROLES,
  CENTRAL_SUPPORT_USER_STATUSES,
  ALL_CENTRAL_SUPPORT_USER_STATUSES,
  CENTRAL_SUPPORT_ERROR_CODES
};
