const CLASSIFICATION_MATCHED_BY = Object.freeze({
  TICKET_REFERENCE: "TICKET_REFERENCE",
  SENDER_EMAIL: "SENDER_EMAIL",
  SUBJECT_KEYWORDS: "SUBJECT_KEYWORDS",
  BODY_KEYWORDS: "BODY_KEYWORDS",
  MANUAL: "MANUAL"
});

const CLASSIFICATION_QUEUE_STATUS = Object.freeze({
  PENDING: "PENDING",
  RESOLVED: "RESOLVED",
  DISMISSED: "DISMISSED"
});

const DEFAULT_CONFIDENCE_THRESHOLD = 0.6;

const MATCH_CONFIDENCE = Object.freeze({
  TICKET_REFERENCE: 1,
  SENDER_EMAIL: 0.92,
  SUBJECT_KEYWORDS_MAX: 0.85,
  BODY_KEYWORDS_MAX: 0.75
});

module.exports = {
  CLASSIFICATION_MATCHED_BY,
  CLASSIFICATION_QUEUE_STATUS,
  DEFAULT_CONFIDENCE_THRESHOLD,
  MATCH_CONFIDENCE
};
