const NOTIFICATION_PROVIDERS = {
  SMTP: "SMTP",
  ELVA_NOTIFY: "ELVA_NOTIFY",
  FALLBACK: "FALLBACK"
};

const DELIVERY_STATUS = {
  SUCCESS: "SUCCESS",
  FAILED: "FAILED"
};

/** Event types processed by NotificationWorker for merchant-facing delivery */
const WORKER_NOTIFICATION_TYPES = {
  TICKET_CREATED: "TICKET_CREATED",
  TICKET_ASSIGNED: "TICKET_ASSIGNED",
  AGENT_REPLY: "AGENT_REPLY",
  STATUS_CHANGED: "STATUS_CHANGED",
  TICKET_RESOLVED: "TICKET_RESOLVED"
};

const OTP_CHANNELS = {
  EMAIL: "email",
  SMS: "sms"
};

/** Future provider identifiers for documentation and configuration */
const FUTURE_PROVIDERS = ["FAST2SMS", "MSG91", "GUPSHUP"];

module.exports = {
  NOTIFICATION_PROVIDERS,
  DELIVERY_STATUS,
  WORKER_NOTIFICATION_TYPES,
  OTP_CHANNELS,
  FUTURE_PROVIDERS
};
