/**
 * Platform administration identity constants (Phase 5).
 * Completely separate from tenant roles (ADMIN / TEAM_LEAD / AGENT).
 */

const PLATFORM_IDENTITY_TYPE = "PLATFORM_ADMIN";

const PLATFORM_ROLES = Object.freeze({
  PLATFORM_SUPER_ADMIN: "PLATFORM_SUPER_ADMIN",
  PLATFORM_ADMIN: "PLATFORM_ADMIN",
  PLATFORM_SUPPORT: "PLATFORM_SUPPORT"
});

const ALL_PLATFORM_ROLES = Object.values(PLATFORM_ROLES);

const PLATFORM_ADMIN_STATUSES = Object.freeze({
  ACTIVE: "ACTIVE",
  INVITED: "INVITED",
  SUSPENDED: "SUSPENDED",
  DISABLED: "DISABLED"
});

const ALL_PLATFORM_ADMIN_STATUSES = Object.values(PLATFORM_ADMIN_STATUSES);

const PLATFORM_AUDIT_ACTIONS = Object.freeze({
  PLATFORM_ADMIN_LOGIN: "PLATFORM_ADMIN_LOGIN",
  PLATFORM_ADMIN_CREATED: "PLATFORM_ADMIN_CREATED",
  PLATFORM_ADMIN_UPDATED: "PLATFORM_ADMIN_UPDATED",
  PLATFORM_ADMIN_STATUS_CHANGED: "PLATFORM_ADMIN_STATUS_CHANGED",
  PLATFORM_ADMIN_ROLE_CHANGED: "PLATFORM_ADMIN_ROLE_CHANGED",
  TENANT_CREATED: "TENANT_CREATED",
  TENANT_UPDATED: "TENANT_UPDATED",
  TENANT_STATUS_CHANGED: "TENANT_STATUS_CHANGED",
  TENANT_SUSPENDED: "TENANT_SUSPENDED",
  TENANT_ACTIVATED: "TENANT_ACTIVATED",
  TENANT_ARCHIVED: "TENANT_ARCHIVED",
  TENANT_PROVISIONING_STARTED: "TENANT_PROVISIONING_STARTED",
  TENANT_PROVISIONING_COMPLETED: "TENANT_PROVISIONING_COMPLETED",
  TENANT_PROVISIONING_FAILED: "TENANT_PROVISIONING_FAILED",
  TENANT_ADMIN_CREATED: "TENANT_ADMIN_CREATED",
  TENANT_ADMIN_INVITED: "TENANT_ADMIN_INVITED",
  TENANT_INVITATION_RESENT: "TENANT_INVITATION_RESENT",
  TENANT_PROVISIONING_RETRIED: "TENANT_PROVISIONING_RETRIED"
});

const PLATFORM_AUDIT_TARGET_TYPES = Object.freeze({
  PLATFORM_ADMIN: "PLATFORM_ADMIN",
  TENANT: "TENANT",
  PROVISIONING: "PROVISIONING",
  TENANT_USER: "TENANT_USER"
});

const PLATFORM_ERROR_CODES = Object.freeze({
  PLATFORM_ADMIN_NOT_FOUND: "PLATFORM_ADMIN_NOT_FOUND",
  PLATFORM_ADMIN_EMAIL_ALREADY_EXISTS: "PLATFORM_ADMIN_EMAIL_ALREADY_EXISTS",
  PLATFORM_ADMIN_INACTIVE: "PLATFORM_ADMIN_INACTIVE",
  INVALID_PLATFORM_ROLE: "INVALID_PLATFORM_ROLE",
  PLATFORM_ACCESS_DENIED: "PLATFORM_ACCESS_DENIED",
  INVALID_TENANT_STATUS_TRANSITION: "INVALID_TENANT_STATUS_TRANSITION",
  TENANT_NOT_FOUND: "TENANT_NOT_FOUND",
  LAST_SUPER_ADMIN_PROTECTED: "LAST_SUPER_ADMIN_PROTECTED",
  INVALID_PLATFORM_CREDENTIALS: "INVALID_PLATFORM_CREDENTIALS"
});

/**
 * Allowed tenant status transitions for platform lifecycle APIs.
 * ARCHIVED is terminal.
 */
const TENANT_STATUS_TRANSITIONS = Object.freeze({
  TRIAL: ["ACTIVE", "SUSPENDED", "CANCELLED"],
  ACTIVE: ["SUSPENDED", "CANCELLED", "TRIAL"],
  SUSPENDED: ["ACTIVE", "CANCELLED"],
  CANCELLED: ["ARCHIVED"],
  ARCHIVED: []
});

module.exports = {
  PLATFORM_IDENTITY_TYPE,
  PLATFORM_ROLES,
  ALL_PLATFORM_ROLES,
  PLATFORM_ADMIN_STATUSES,
  ALL_PLATFORM_ADMIN_STATUSES,
  PLATFORM_AUDIT_ACTIONS,
  PLATFORM_AUDIT_TARGET_TYPES,
  PLATFORM_ERROR_CODES,
  TENANT_STATUS_TRANSITIONS
};
