/**
 * Tenant provisioning constants (Phase 6).
 * Separate from Tenant.status and PlatformAdmin statuses.
 */

const PROVISIONING_STATUSES = Object.freeze({
  PENDING: "PENDING",
  IN_PROGRESS: "IN_PROGRESS",
  READY: "READY",
  FAILED: "FAILED"
});

const ALL_PROVISIONING_STATUSES = Object.values(PROVISIONING_STATUSES);

const PROVISIONING_STEP_KEYS = Object.freeze({
  TENANT_CREATED: "tenantCreated",
  WORKSPACE_INITIALIZED: "workspaceInitialized",
  ADMIN_CREATED: "adminCreated",
  INVITATION_CREATED: "invitationCreated",
  WELCOME_EMAIL: "welcomeEmail"
});

const PROVISIONING_STEP_STATUSES = Object.freeze({
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  SKIPPED: "SKIPPED"
});

const INVITATION_STATUSES = Object.freeze({
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  EXPIRED: "EXPIRED",
  REVOKED: "REVOKED"
});

const ALL_INVITATION_STATUSES = Object.values(INVITATION_STATUSES);

const PROVISIONING_ERROR_CODES = Object.freeze({
  PROVISIONING_NOT_FOUND: "PROVISIONING_NOT_FOUND",
  PROVISIONING_CONFLICT: "PROVISIONING_CONFLICT",
  PROVISIONING_NOT_RETRIABLE: "PROVISIONING_NOT_RETRIABLE",
  INVALID_INVITATION: "INVALID_INVITATION",
  INVITATION_EXPIRED: "INVITATION_EXPIRED",
  INVITATION_ALREADY_USED: "INVITATION_ALREADY_USED",
  TENANT_ADMIN_EMAIL_EXISTS: "TENANT_ADMIN_EMAIL_EXISTS",
  INVALID_PASSWORD: "INVALID_PASSWORD"
});

const defaultProvisioningSteps = () => ({
  [PROVISIONING_STEP_KEYS.TENANT_CREATED]: { status: PROVISIONING_STEP_STATUSES.PENDING },
  [PROVISIONING_STEP_KEYS.WORKSPACE_INITIALIZED]: { status: PROVISIONING_STEP_STATUSES.PENDING },
  [PROVISIONING_STEP_KEYS.ADMIN_CREATED]: { status: PROVISIONING_STEP_STATUSES.PENDING },
  [PROVISIONING_STEP_KEYS.INVITATION_CREATED]: { status: PROVISIONING_STEP_STATUSES.PENDING },
  [PROVISIONING_STEP_KEYS.WELCOME_EMAIL]: { status: PROVISIONING_STEP_STATUSES.PENDING }
});

module.exports = {
  PROVISIONING_STATUSES,
  ALL_PROVISIONING_STATUSES,
  PROVISIONING_STEP_KEYS,
  PROVISIONING_STEP_STATUSES,
  INVITATION_STATUSES,
  ALL_INVITATION_STATUSES,
  PROVISIONING_ERROR_CODES,
  defaultProvisioningSteps
};
